#!/bin/bash

# function: read downstream profile, and compare with different file.
# input: the directory name,which you want to compare
# output: the multiplot figure
# example:
# gn2 3MW/ cflmi/

# =========== get the current path ====================#
fp=`pwd`
# Thanks for interactive shell,we get the directory name 
# ${1} specify the first input variable, ${n} is similar

# ============ catch the path,which is used for plot====#
pp1="${fp}/${1}" 
pp2="${fp}/${2}"
#echo "${pp1}"

# =============== get the basename for legend ==========#
leg1=${1}
leg2=${2}

# ============== gnuplot function =====================#

echo "
set term post eps color solid enh
set output 'base2.eps'

set multiplot title 'downstream profiles' layout 4,2

plot '${pp1}te3dl.last10' w l t '${leg1}te3dl','${pp2}te3dl.last10' w l t '${leg2}
plot '${pp1}te3dr.last10' w l t '${leg1}te3dr','${pp2}te3dr.last10' w l t '${leg2}

plot '${pp1}ne3dl.last10' w l t '${leg1}ne3dl','${pp2}ne3dl.last10' w l t '${leg2}
plot '${pp1}ne3dr.last10' w l t '${leg1}ne3dr','${pp2}ne3dr.last10' w l t '${leg2}

plot '${pp1}ft3dl.last10' w l t '${leg1}ft3dl','${pp2}ft3dl.last10' w l t '${leg2}
plot '${pp1}ft3dr.last10' w l t '${leg1}ft3dr','${pp2}ft3dr.last10' w l t '${leg2}

plot '${pp1}fn3dl.last10' w l t '${leg1}fn3dl','${pp2}fn3dl.last10' w l t '${leg2}
plot '${pp1}fn3dr.last10' w l t '${leg1}fn3dr','${pp2}fn3dr.last10' w l t '${leg2}

unset multiplot
" | gnuplot
echo "downstream profiles are saved as base2.eps"

