#!/bin/bash
mkdir 2D_data

# function： get the mprt file

## parameters

	# zeff
echo "phys eirc zeff 'zeff_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/zeff_2D.last10 2D_data


# ======================================== flux ======================================== #
	# fnax
echo "phys eirc fnax 'fnax_2D.last10' mprt" | b2plot;mv  b2pl.exe.dir/fnax_2D.last10 2D_data 
	# fhtx
echo "phys eirc fhtx 'fhtx_2D.last10' mprt" | b2plot;mv  b2pl.exe.dir/fhtx_2D.last10 2D_data 

# ===================================== radiation ====================================== #	
	# b2ra
echo "phys eirc b2ra abs 'b2ra_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/b2ra_2D.last10 2D_data
	# b2br
echo "phys eirc b2br abs 'b2br_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/b2br_2D.last10 2D_data
	# brna
echo "phys eirc brna 'brna_2D.last10' mprt " | b2plot ;
 mv b2pl.exe.dir/brna_2D.last10 2D_data

# ======================================= te =========================================== #
	# temperature
echo "te 'te_2D.last10' mprt" | b2plot; 
mv b2pl.exe.dir/te_2D.last10 2D_data
echo "ti 'ti_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/ti_2D.last10 2D_data
echo "tab2 'tab2_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/tab2_2D.last10 2D_data
echo "tmb2 'tmb2_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/tmb2_2D.last10 2D_data

# ====================================== density ======================================== #
	# density
echo "phys eirc dmb2 'dmb2_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/dmb2_2D.last10 2D_data
echo "phys eirc dab2 'dab2_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/dab2_2D.last10 2D_data
echo "phys eirc na 'na_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/na_2D.last10 2D_data
#echo "phys eirc pdena  'pdena_eir.last10' eprt " | b2plot ;
#mv b2pl.exe.dir/pdena_eir.last10 2D_data

# ===================================== pressure ======================================== #
	# pressure
echo "eirc pr 'pr_2D.last10' mprt" | b2plot;mv b2pl.exe.dir/pr_2D.last10 2D_data
echo "eirc p* 'pt_2D.last10' mprt" | b2plot;mv b2pl.exe.dir/pt_2D.last10 2D_data
echo "phys pr ddx  'gp_2D.last10' mprt" | b2plot;mv b2pl.exe.dir/gp_2D.last10 2D_data	
echo "phys p* ddx  'gpt_2D.last10' mprt" | b2plot;mv b2pl.exe.dir/gpt_2D.last10 2D_data	
	

# ===================================== force =========================================== #	
	# force
echo "phys eirc smp 'smp_2D.last10' mprt " | b2plot ;
 mv b2pl.exe.dir/smp_2D.last10 2D_data
echo "phys eirc smth 'smth_2D.last10' mprt " | b2plot ;
 mv b2pl.exe.dir/smth_2D.last10 2D_data
echo "phys eirc smfr 'smfr_2D.last10' mprt " | b2plot ;
 mv b2pl.exe.dir/smfr_2D.last10 2D_data

# ================================== electric potential ================================== #
echo "po ddx 'Ep_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/Ep_2D.last10 2D_data
echo "po ddy 'Er_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/Er_2D.last10 2D_data
echo "po  'po_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/po_2D.last10 2D_data
# =====================================  velocity ======================================== #
echo "up 1 zsel 'vp_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/vp_2D.last10 2D_data
echo "vv 1 zsel 'vr_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/vr_2D.last10 2D_data
echo "ww 1 zsel 'vz_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/vz_2D.last10 2D_data
echo "ua 1 zsel 'ua_2D.last10' mprt" | b2plot;
 mv b2pl.exe.dir/ua_2D.last10 2D_data
 echo "phys eirc mach 'mach_2D.last10' mprt " | b2plot ;
 mv b2pl.exe.dir/mach_2D.last10 2D_data

# ======================================= mass density ==================================== #
echo "phys eirc ro 'ro_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/ro_2D.last10 2D_data

## combination

# ========================================= radiation ===================================== #
	# carbon radiation of every layer
echo "phys eirc b2ra b2br m+ 'b2rabr_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/b2rabr_2D.last10 2D_data
	# total radiation
echo "phys brna 0.0 rmma pot m* 0 0 sumz ev rm* -1.0 rm* brhe m- b2ra 0 0 sumz m+ b2br 0 0 sumz m+ 'rad_dc_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/rad_dc_2D.last10 2D_data
   	 # total carbon radiation
echo "phys b2ra 2 8 sumz b2br 2 8 sumz m+ 'rad_c_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/rad_c_2D.last10 2D_data

# ======================================== flux ============================================ #
	# q_dep
echo "phys eirc fhtx 0 0 sumz psx 'q_dep_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/q_dep_2D.last10 2D_data
	# f_dep
echo "phys eirc fnax 0 0 sumz psx 'f_dep_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/f_dep_2D.last10 2D_data
	# q_per
echo "phys eirc fhtx 0 0 sumz psxperp 'q_per_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/q_per_2D.last10 2D_data
	# f_per
echo "phys eirc fnax 0 0 sumz psxperp 'f_per_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/f_per_2D.last10 2D_data
	# q_par
echo "phys eirc fhtx 0 0 sumz psxperp pit m/  'q_par_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/q_par_2D.last10 2D_data
	# f_par
echo "phys eirc fnax 0 0 sumz psxperp pit m/  'f_par_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/f_par_2D.last10 2D_data
	# jsat
echo "phys eirc fnax 0 0 sumz psxperp pit m/ 6.24e22 rm/  'jsat_2D.last10' mprt " | b2plot ;
mv b2pl.exe.dir/jsat_2D.last10 2D_data
# ============================  neutral pressure =================================== #
 echo "phys eirc dab2 abs 0 zsel eirc tab2 abs 0 zsel m*  eirc dab2 abs 2 zsel eirc tab2 abs 2 zsel m* m+ eirc dab2 abs 1 zsel eirc tab2 abs 1 zsel m* m+   1.6e19 rm/ 'pneu_c_2D.last10' mprt" | b2plot; 
 mv b2pl.exe.dir/pneu_c_2D.last10 2D_data






