#!/bin/bash

# function read in the list value 
# copy the specified case to the list name
# for function read in the list 

# step 1 for
path=`pwd`
read -p  "Please enter the case_list file name:(e.g. case_name)" input
while IFS=' ' read -r cn
do
	echo "qsub ${cn}!"
	cd ${path}/${cn}
	echo `pwd`
	cp b2fstate b2fstate.cp;
	cp b2fstati b2fstati.cp;
	cp b2fstate b2fstati;
	sbatch SLURM.DUT-PSI-forSOLPS
done < "$input"
echo "qsub  case  success!"
