#!/bin/bash

# sepcify the father path of case cluster
path=${1}

# specify the string, containning in casename

if [ $# -lt 1 ] ; then
	echo "Please enter the path. "
	exit 0
elif [ $# -gt 1 ]; then
	cn=${2}
else	
	cn='MW' # default value
fi


# get the case_namelist, which you want to read 
rm case_namelist &>  /dev/null

ls ${path} | awk '/'${cn}'/ {print $0}' > case_namelist
while read -r case_name
do
	case_path="${path}/${case_name}"
	if [ -d ${case_path} ]
	then
		cd "${path}/${case_name}"

		# ====== callback your scripts in here ======== #

#		most_add
#		mat2d_pro
#		most_data






		# ============================================= #
	else
		echo "Please check ${case_name}, which is no a directroy."
	fi
done < case_namelist
