#!bin/bash
#echo '
#set term postscript eps enhanced
#set output "enhanced.eps"

#set style data linespoints
#set key top right
#set xlabel "r-r_{sep}(m)"
#set ylabel "ft3dr"
#plot "ft3dr.last10"
#' | gnuplot
echo '
 
set term post eps color solid enh
set output "ups.eps"

set multiplot title "upstream profiles" layout 2,2
set mxtics 5
set mytics 5
plot "te3di.last10" using 1:(abs($2))  w l ti "ti3di" 
plot "te3da.last10" using 1:(abs($2))  w l ti "ti3da"

plot "ne3di.last10" using 1:(abs($2))  w l ti "ne3di"
plot "ne3da.last10" using 1:(abs($2))  w l ti "ne3da"

#plot "ft3di.last10"  w l
#plot "ft3da.last10"  w l

#plot "fn3di.last10"  w l
#plot "fn3da.last10"  w l

unset multiplot
' | gnuplot

